### ISSUE TITLE
API credentials not loading from .env file

### ISSUE THREAD

**Issue by vighneshtrivedi2004** [Paubox/paubox-php#5] opened 2019-06-25 10:36 UTC
Hi, Vighnesh,

The scope matter seems good now but I seem to only be getting a "not found" message back from SendMessageResponse()->sendMessage($Message) in the sample code.

stdClass Object
(
    [status] => 404
    [error] => Not Found
)

I still seem to be missing something?  The .env has both api key and endpoint...might I have it in the wrong place ... ie where does paubox look for it?

Thanks!

To schedule an appointment with me click the link below:
http://www.scheduleyou.in/cDuj38m

[1455739291530_johnBorelliLogo.jpg]

John Borelli
Lead Programmer
The Plan B Club, LLC
john@theplanbclub.com
1 866 975 7526 x 702

**Comment by vighneshtrivedi2004** [comment] 2019-06-25 10:55
Hi John,

Thank you for reporting the issue. This issue has occurred as the API credentials are not getting loaded from .env file. To fix this issue, please install the following dependency:

```bash
$ composer require vlucas/phpdotenv
```

And add the following lines after including autoload.php file:

```php
$dotenv = Dotenv\Dotenv::create(__DIR__);
$dotenv->load();
```

This will load the .env file, and you will be able to successfully call the sendMessage method.

Regards,
Vighnesh

**Comment by vighneshtrivedi2004** [comment] 2019-06-28 05:06
Hi John,

Would you please confirm if this issue is fixed for you?

Regards,
Vighnesh

**Comment by JohnBorelliApproved** [comment] 2019-06-28 14:39
Hi, Vighnesh,

I had a medical issue that kept me out of work for the past couple of days so I'll need to try the above solution and I'll let you know how it goes. 

Thanks for all the help ;)

**Comment by JohnBorelliApproved** [comment] 2019-07-01 16:44
Hi, Vighnesh,

I've followed the above and still get the same message.  I then copied the .env into every folder drilling down to the vendor/paubox folder to ensure it was in the right place and still the same message.  Where EXACTLY in the path is the .env supposed to be?

**Comment by vighneshtrivedi2004** [comment] 2019-07-02 06:12
Hi John,

The .env file should be added to the root of your project. Please delete the .env file from all other locations.

The location of the .env file needs to be passed as a parameter to the create function of Dotenv. So, if your source php file is present in the project root directory, then you need to configure the root directory path in Dotenv as shown below:

```php
$dotenv = Dotenv\Dotenv::create(__DIR__);
$dotenv->load();
```
But if your source php file is present in any other subdirectory within the project root directory, then you need to configure Dotenv as shown below:

```php
$BASE_DIR = "D:/TestProjects/YourProjectRootDirectory";

$dotenv = Dotenv\Dotenv::create($BASE_DIR);
$dotenv->load();

```
Please let me know if this solves your issue.

Regards,
Vighnesh

**Comment by JohnBorelliApproved** [comment] 2019-07-02 13:22
Vighnesh,


Thank you VERY much!  I'll give this a go this afternoon 😉


To schedule an appointment with me click the link below:
http://www.scheduleyou.in/cDuj38m

[1455739291530_johnBorelliLogo.jpg]

John Borelli
Lead Programmer
The Plan B Club, LLC
john@theplanbclub.com
1 866 975 7526 x 702
________________________________

**Comment by vighneshtrivedi2004** [comment] 2019-07-08 05:21
Hi John,

Would you please confirm if this issue is fixed for you?

Regards,
Vighnesh

**Comment by JohnBorelliApproved** [comment] 2019-07-08 19:41
Hi, Vighnesh,

Actually, our internet has been down for about a week and while they have come out, they had to schedule a return visit to fix it which is supposed to happen sometime tomorrow afternoon...so needless to say, I'm quite behind on a lot of things because of this.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by JohnBorelliApproved** [comment] 2019-07-15 02:50
Hi, Vighnesh,


Thanks for all your patience thus far 😉


Everything "LOOKS" right but I'm still getting the same response? (see image in phpStorm)


[cid:e196e63c-21e4-4ede-b001-91d92395f52f]


Thanks!

To schedule an appointment with me click the link below:
http://www.scheduleyou.in/cDuj38m

[1455739291530_johnBorelliLogo.jpg]

John Borelli
Lead Programmer
The Plan B Club, LLC
john@theplanbclub.com
1 866 975 7526 x 702
________________________________

**Comment by vighneshtrivedi2004** [comment] 2019-07-15 05:47
Hi John,

I am not able to see the phpStorm image attached in the previous message. Would you please upload to Dropbox and share Dropbox link with me?

Regards,
Vighnesh

**Comment by JohnBorelliApproved** [comment] 2019-07-15 14:30
Hey, Vighnesh,


Dropbox shared link to image below 😉


https://www.dropbox.com/s/00p7jlpqlvt8tq0/pauboxExampleCode.PNG?dl=0



To schedule an appointment with me click the link below:
http://www.scheduleyou.in/cDuj38m

[1455739291530_johnBorelliLogo.jpg]

John Borelli
Lead Programmer
The Plan B Club, LLC
john@theplanbclub.com
1 866 975 7526 x 702
________________________________

**Comment by vighneshtrivedi2004** [comment] 2019-07-16 06:37
Hi John,

Thanks for sharing the image. The code in test.php file looks good. 

It seems that the value of PAUBOX_API_USER variable might not be correct. If you have set the value of environment variable PAUBOX_API_USER as 'https://api.paubox.net/v1/YOUR_API_USER/', then please change the value to only 'YOUR_API_USER'

Please let me know if this fixes the issue.

Regards,
Vighnesh

**Comment by JohnBorelliApproved** [comment] 2019-07-16 13:01
Hi, Vighnesh,


Thanks for checking me and I'm glad to hear you confirm the code looks right.  Of course the credentials are the next logical step 😉


I've uploaded an image of the .env file...maybe I missed something obvious there?


https://www.dropbox.com/s/bj4uhwwuu6uat82/dotenv.PNG?dl=0

[https://www.dropbox.com/temp_thumb_from_token/s/bj4uhwwuu6uat82?preserve_transparency=False&size=1200x1200&size_mode=4]<https://www.dropbox.com/s/bj4uhwwuu6uat82/dotenv.PNG?dl=0>
dotenv.PNG<https://www.dropbox.com/s/bj4uhwwuu6uat82/dotenv.PNG?dl=0>
www.dropbox.com
Shared with Dropbox

Thanks!


To schedule an appointment with me click the link below:
http://www.scheduleyou.in/cDuj38m

[1455739291530_johnBorelliLogo.jpg]

John Borelli
Lead Programmer
The Plan B Club, LLC
john@theplanbclub.com
1 866 975 7526 x 702
________________________________

**Comment by vighneshtrivedi2004** [comment] 2019-07-17 05:23
Hi John,

Thanks for sharing the image of .env file. 

As mentioned in my previous message, the value of PAUBOX_API_USER variable should not contain the complete endpoint URL.  It should only have the API Username, i.e, the part after /v1/ in your .env file.  So , please change the value of PAUBOX_API_USER to '<YOUR_API_USER>'  in your .env file.

Also, please delete the .env file link from Dropbox, as it can expose your API credentials.

Regards,
Vighnesh

**Comment by vighneshtrivedi2004** [comment] 2019-07-19 04:19
Hi John,

Would you please confirm if the above solution fixed your issue?

Regards,
Vighnesh

**Comment by JohnBorelliApproved** [comment] 2019-07-19 11:42
Hi, Vighnesh,


Thanks for checking 😉.  I was trying a few things before bothering you again lol


So I did get a different result but it's saying that it's an invalid user name.  I tried the user name alone, and with forward slash before and/or after (just to be sure I understood right) and this is the message I'm now getting:


[cid:33da4e68-3c7d-45ff-b69b-1ee2ff3b5115]


To schedule an appointment with me click the link below:
http://www.scheduleyou.in/cDuj38m

[1455739291530_johnBorelliLogo.jpg]

John Borelli
Lead Programmer
The Plan B Club, LLC
john@theplanbclub.com
1 866 975 7526 x 702
________________________________

**Comment by vighneshtrivedi2004** [comment] 2019-07-20 05:00
Hi John,

I am unable to see the image attached in the previous message.  But I understand you are getting a 
Invalid Endpoint Username error. Please check if your PAUBOX_API_USER is valid. 

Below is a sample .env file:
```
export PAUBOX_API_KEY='testkey'
export PAUBOX_API_USER='testuser'
```

Please let me know if your issue is fixed with valid api_user.

Regards,
Vighnesh

**Comment by JohnBorelliApproved** [comment] 2019-07-20 06:08
Hi, Vighnesh,


I removed the image at your last suggestion.  The PAUBOX_API_USER='zkorwin' is what's being used.  The key I got from, Zach, the client, ending in 7aa0


To schedule an appointment with me click the link below:
http://www.scheduleyou.in/cDuj38m

[1455739291530_johnBorelliLogo.jpg]

John Borelli
Lead Programmer
The Plan B Club, LLC
john@theplanbclub.com
1 866 975 7526 x 702
________________________________

**Comment by robogus** [comment] 2019-07-22 20:37
Hi John,

This is Robert from the Paubox Support team.  We are not seeing "zworkin" as a valid API username.  You will want to pass the API username for the domain that is configured in the Paubox admin panel.  **Here’s how to find that information:**

* Log in to the Paubox admin panel (https://www.paubox.com/users/sign_in)
* Navigate to Developer > REST API > Manage Your Domains / API Credentials
* Look for a gear icon on the right side of the domain name that you are sending from and click this.  Select "Domain Settings"
* On the Domain Settings page, under the Domain Info section, you will see something that says "API Base URL" and will be in this format:

https://api.paubox.net/v1/<API USERNAME>

That's where you can find the API username to pass.

Hope that helps.  If I can be of further assistance with this, just let me know.

Thanks,
Robert

**Comment by JohnBorelliApproved** [comment] 2019-07-23 14:28
Hi Robert,

Thanks for the followup.  Zach has determined the correct id and it looks like we've passed that hurdle.  However, code is now returning a message saying that the domain is not approved for sending...since I have to first develop for Zach, I need to know how to get my dev domain approved.  Is there some place in the app that specifies this?

Thanks again 😉

To schedule an appointment with me click the link below:
http://www.scheduleyou.in/cDuj38m

[1455739291530_johnBorelliLogo.jpg]

John Borelli
Lead Programmer
The Plan B Club, LLC
john@theplanbclub.com
1 866 975 7526 x 702

________________________________

**Comment by robogus** [comment] 2019-07-23 18:51
Hi John,

You are very welcome.  Glad to hear that the correct username was identified.  Please keep in mind that the API username is different for each domain that you configure in the Paubox admin panel.  If you are adding a new domain name there (the dev domain), use the API username value for that domain.

You mentioned that you are getting an error saying that the domain is not approved for sending.  Here's how to add/validate a domain in the Paubox admin panel:

	•	Log in to the Paubox admin panel (https://www.paubox.com/users/sign_in)
	•	Navigate to Developer > REST API > Manage Your Domains / API Credentials
	•	Click the “Add New Domain” button
	•	Enter the domain name that you want to validate for sending through the Paubox REST API and then click the “Add” button
	•	Follow the instructions for adding DNS records at your domain hosting provider for the domain name in question.  Once the DNS records have been added and confirmed, the status of the domain will show as “Active” in the Paubox admin panel.

If you could use help with any of this, just let me know.

Thanks,
Robert

**Comment by JohnBorelliApproved** [comment] 2019-08-08 13:57
Hey, guys,

I think I have only one last issue I have to figure out as PB is working for sending encrypted for us now.  This client would like to use the script for multiple senders, which obviously means using multiple api keys.  Dotenv uses the environment file and I had thought that there would be a way to "push" an api key and name to allow for varying senders but I'm not seeing anything that would do this in dotenv or paubox's methods that are exposed?

Since I'm sure we can't be the first to have need for this, I'm sure there must be a way to dynamically assign the name/key?  So how might one go about doing this?

Thanks so much in advance for any help ;)

**Comment by TomatoOmelette** [comment] 2019-08-15 21:30
I apologize, but this isn't a feature that we currently support with this SDK.

One option is to handle the requests directly to the API yourself without using the SDK. You could build a class that handles the request and is instantiated with arguments for the API key and endpoint username. You could also fork the SDK and change it to your liking.

**Closed as completed by TomatoOmelette** 2019-08-15 21:30 UTC
